use rustpython_parser::ast::{self, Expr, Ranged, Stmt};

use fastapi_doctor_core::{Issue, ModuleRecord, parse_suite};
use fastapi_doctor_core::ast_helpers::walk_suite_exprs;

// ── Helpers ──────────────────────────────────────────────────────────────────

fn is_configure_call(call: &ast::ExprCall) -> bool {
    match &*call.func {
        Expr::Attribute(a) => a.attr.as_str() == "configure",
        _ => false,
    }
}

fn keyword_value<'a>(call: &'a ast::ExprCall, arg_name: &str) -> Option<&'a Expr> {
    call.keywords.iter().find_map(|kw| {
        if kw.arg.as_deref() == Some(arg_name) {
            Some(&*kw.value)
        } else {
            None
        }
    })
}

fn is_none_expr(expr: &Expr) -> bool {
    match expr {
        Expr::NoneLiteral(_) => true,
        Expr::Name(n) => n.id.as_str() == "None",
        _ => false,
    }
}

fn has_keyword(call: &ast::ExprCall, arg_name: &str) -> bool {
    call.keywords
        .iter()
        .any(|kw| kw.arg.as_deref() == Some(arg_name))
}

/// Returns (has_active_configure, has_process_revision_directives, configure_line)
/// "active" = configure() with a non-None target_metadata
fn analyze_alembic_env(suite: &ast::Suite) -> (bool, bool, usize) {
    let mut active_configure_line: Option<usize> = None;
    let mut has_process_revision = false;

    walk_suite_exprs(suite, &mut |expr| {
        let Expr::Call(call) = expr else { return };
        if !is_configure_call(call) {
            return;
        }
        let Some(tm_value) = keyword_value(call, "target_metadata") else {
            return;
        };
        if is_none_expr(tm_value) {
            return;
        }
        // Active configure() call found
        let line = call.range.start().to_usize();
        if active_configure_line.is_none() {
            active_configure_line = Some(line);
        }
        if has_keyword(call, "process_revision_directives") {
            has_process_revision = true;
        }
    });

    match active_configure_line {
        Some(line) => (true, has_process_revision, line),
        None => (false, false, 0),
    }
}

// ── Public rule functions ─────────────────────────────────────────────────────

/// config/alembic-target-metadata: env.py should wire target_metadata to a real object.
pub(crate) fn check_alembic_target_metadata(
    source: &str,
    rel_path: &str,
) -> Option<Issue> {
    let suite = rustpython_parser::parse(source, rustpython_parser::Mode::Module, "<alembic>")
        .ok()
        .and_then(|m| match m {
            ast::Mod::Module(m) => Some(m.body),
            _ => None,
        })?;

    // Check if there's any configure() call at all, and if any has a non-None target_metadata
    let mut has_any_configure = false;
    let mut has_active_target_metadata = false;
    let mut first_configure_line = 1usize;

    walk_suite_exprs(&suite, &mut |expr| {
        let Expr::Call(call) = expr else { return };
        if !is_configure_call(call) {
            return;
        }
        if !has_any_configure {
            has_any_configure = true;
            first_configure_line = call.range.start().to_usize();
        }
        if let Some(tm) = keyword_value(call, "target_metadata") {
            if !is_none_expr(tm) {
                has_active_target_metadata = true;
            }
        }
    });

    if !has_any_configure || has_active_target_metadata {
        return None;
    }

    Some(Issue {
        check: "config/alembic-target-metadata",
        severity: "warning",
        category: "Config",
        line: first_configure_line,
        path: rel_path.to_string(),
        message: "Alembic env.py does not pass a real target_metadata object for autogenerate",
        help: "Import your SQLAlchemy or SQLModel metadata and pass it to context.configure(target_metadata=...).",
    })
}

/// config/alembic-empty-autogen-revision: configure() should use process_revision_directives.
pub(crate) fn check_alembic_empty_autogen_revision(
    source: &str,
    rel_path: &str,
) -> Option<Issue> {
    let suite = rustpython_parser::parse(source, rustpython_parser::Mode::Module, "<alembic>")
        .ok()
        .and_then(|m| match m {
            ast::Mod::Module(m) => Some(m.body),
            _ => None,
        })?;

    let (has_active, has_process_revision, configure_line) = analyze_alembic_env(&suite);
    if !has_active || has_process_revision {
        return None;
    }

    Some(Issue {
        check: "config/alembic-empty-autogen-revision",
        severity: "warning",
        category: "Config",
        line: configure_line,
        path: rel_path.to_string(),
        message: "Alembic autogenerate will still create empty revisions",
        help: "Wire process_revision_directives in env.py and drop empty autogenerated revisions before the file is written.",
    })
}

fn has_naming_convention(modules: &[ModuleRecord]) -> bool {
    for module in modules {
        if !module.source.contains("naming_convention") {
            continue;
        }
        let Ok(parsed) = rustpython_parser::parse(
            &module.source,
            rustpython_parser::Mode::Module,
            "<module>",
        ) else {
            continue;
        };
        let ast::Mod::Module(m) = parsed else { continue };
        let mut found = false;
        walk_suite_exprs(&m.body, &mut |expr| {
            let Expr::Call(call) = expr else { return };
            let is_metadata = match &*call.func {
                Expr::Name(n) => n.id.as_str() == "MetaData",
                Expr::Attribute(a) => a.attr.as_str() == "MetaData",
                _ => false,
            };
            if is_metadata && has_keyword(call, "naming_convention") {
                found = true;
            }
        });
        // Also check for `<name>.naming_convention = ...` assignments
        if !found {
            walk_naming_convention_assign(&m.body, &mut |_| {
                found = true;
            });
        }
        if found {
            return true;
        }
    }
    false
}

fn walk_naming_convention_assign(stmts: &[Stmt], cb: &mut impl FnMut(usize)) {
    for stmt in stmts {
        match stmt {
            Stmt::Assign(a) => {
                for target in &a.targets {
                    if let Expr::Attribute(attr) = target {
                        if attr.attr.as_str() == "naming_convention" {
                            cb(a.range.start().to_usize());
                        }
                    }
                }
            }
            Stmt::AnnAssign(a) => {
                if let Expr::Attribute(attr) = &*a.target {
                    if attr.attr.as_str() == "naming_convention" {
                        cb(a.range.start().to_usize());
                    }
                }
            }
            Stmt::If(i) => {
                walk_naming_convention_assign(&i.body, cb);
                walk_naming_convention_assign(&i.orelse, cb);
            }
            Stmt::FunctionDef(f) => walk_naming_convention_assign(&f.body, cb),
            Stmt::AsyncFunctionDef(f) => walk_naming_convention_assign(&f.body, cb),
            Stmt::ClassDef(c) => walk_naming_convention_assign(&c.body, cb),
            _ => {}
        }
    }
}

/// config/sqlalchemy-naming-convention: alembic-managed metadata should use naming conventions.
pub(crate) fn check_sqlalchemy_naming_convention(
    alembic_env_sources: &[(String, String)], // (source, rel_path)
    project_modules: &[ModuleRecord],
) -> Option<Issue> {
    // Only report if there's an active alembic env with non-None target_metadata
    let active_env = alembic_env_sources.iter().find_map(|(source, rel_path)| {
        let suite = rustpython_parser::parse(source, rustpython_parser::Mode::Module, "<alembic>")
            .ok()
            .and_then(|m| match m {
                ast::Mod::Module(m) => Some(m.body),
                _ => None,
            })?;
        let (has_active, _, line) = analyze_alembic_env(&suite);
        if has_active {
            Some((rel_path.clone(), line))
        } else {
            None
        }
    });

    let (env_path, env_line) = active_env?;

    if has_naming_convention(project_modules) {
        return None;
    }

    Some(Issue {
        check: "config/sqlalchemy-naming-convention",
        severity: "warning",
        category: "Config",
        line: env_line,
        path: env_path,
        message: "Alembic-managed metadata has no SQLAlchemy naming_convention",
        help: "Set MetaData(naming_convention=...) on your DeclarativeBase or SQLModel metadata so constraint names stay deterministic.",
    })
}
