use std::collections::HashMap;

use fastapi_doctor_core::ast_helpers::{walk_suite_exprs, walk_suite_stmts};
use fastapi_doctor_core::{parse_suite, Issue, ModuleIndex, ModuleRecord};
use rustpython_parser::ast::{self, Expr, Ranged, Stmt};

use crate::engine::RuleSelection;

#[derive(Clone, Copy)]
struct ConfigureCallFacts {
    line: usize,
    target_metadata_non_none: bool,
    has_process_revision_directives: bool,
}

struct AlembicEnvFacts {
    path: String,
    configure_calls: Vec<ConfigureCallFacts>,
}

pub(crate) fn collect_project_configuration_issues(
    modules: &[ModuleRecord],
    rules: &RuleSelection,
) -> Vec<Issue> {
    if !rules.config_alembic_target_metadata
        && !rules.config_alembic_empty_autogen_revision
        && !rules.config_sqlalchemy_naming_convention
    {
        return Vec::new();
    }

    let envs: Vec<AlembicEnvFacts> = modules
        .iter()
        .filter(|module| is_alembic_env_module(module))
        .filter_map(extract_alembic_env_facts)
        .collect();
    if envs.is_empty() {
        return Vec::new();
    }

    let has_naming_convention = rules.config_sqlalchemy_naming_convention
        && modules.iter().any(module_has_naming_convention);

    let mut issues = Vec::new();

    if rules.config_alembic_target_metadata {
        for env in &envs {
            if env
                .configure_calls
                .iter()
                .any(|call| call.target_metadata_non_none)
            {
                continue;
            }
            issues.push(Issue {
                check: "config/alembic-target-metadata",
                severity: "warning",
                category: "Config",
                line: env.configure_calls.first().map_or(1, |call| call.line),
                path: env.path.clone(),
                message:
                    "Alembic env.py does not pass a real target_metadata object for autogenerate",
                help: "Import your SQLAlchemy or SQLModel metadata and pass it to context.configure(target_metadata=...).",
            });
        }
    }

    if rules.config_alembic_empty_autogen_revision {
        for env in &envs {
            let Some(active_call) = env
                .configure_calls
                .iter()
                .find(|call| call.target_metadata_non_none)
            else {
                continue;
            };
            if env
                .configure_calls
                .iter()
                .any(|call| call.target_metadata_non_none && call.has_process_revision_directives)
            {
                continue;
            }
            issues.push(Issue {
                check: "config/alembic-empty-autogen-revision",
                severity: "warning",
                category: "Config",
                line: active_call.line,
                path: env.path.clone(),
                message: "Alembic autogenerate will still create empty revisions",
                help: "Wire process_revision_directives in env.py and drop empty autogenerated revisions before the file is written.",
            });
        }
    }

    if rules.config_sqlalchemy_naming_convention && !has_naming_convention {
        if let Some((env, active_call)) = envs.iter().find_map(|env| {
            env.configure_calls
                .iter()
                .find(|call| call.target_metadata_non_none)
                .map(|call| (env, call))
        }) {
            issues.push(Issue {
                check: "config/sqlalchemy-naming-convention",
                severity: "warning",
                category: "Config",
                line: active_call.line,
                path: env.path.clone(),
                message: "Alembic-managed metadata has no SQLAlchemy naming_convention",
                help: "Set MetaData(naming_convention=...) on your DeclarativeBase or SQLModel metadata so constraint names stay deterministic.",
            });
        }
    }

    issues
}

fn is_alembic_env_module(module: &ModuleRecord) -> bool {
    let path_parts: Vec<&str> = module.rel_path.split('/').collect();
    matches!(path_parts.last(), Some(&"env.py"))
        && path_parts
            .iter()
            .any(|part| matches!(*part, "alembic" | "migrations"))
}

fn extract_alembic_env_facts(module: &ModuleRecord) -> Option<AlembicEnvFacts> {
    let suite = parse_suite(module)?;
    let index = ModuleIndex::new(module);
    let bindings = module_level_bindings(&index, &suite);
    let mut configure_calls = Vec::new();

    walk_suite_exprs(&suite, &mut |expr| {
        let Expr::Call(call) = expr else {
            return;
        };
        let Expr::Attribute(func) = &*call.func else {
            return;
        };
        if func.attr.as_str() != "configure" {
            return;
        }

        let mut target_metadata_non_none = false;
        let mut has_process_revision_directives = false;
        for keyword in &call.keywords {
            match keyword.arg.as_deref() {
                Some("target_metadata") => {
                    target_metadata_non_none =
                        !expr_is_none_like(&index, &keyword.value, &bindings);
                }
                Some("process_revision_directives") => {
                    has_process_revision_directives = true;
                }
                _ => {}
            }
        }

        configure_calls.push(ConfigureCallFacts {
            line: index.line_for_offset(call.range.start().to_usize()),
            target_metadata_non_none,
            has_process_revision_directives,
        });
    });

    Some(AlembicEnvFacts {
        path: module.rel_path.clone(),
        configure_calls,
    })
}

fn module_level_bindings(index: &ModuleIndex<'_>, suite: &ast::Suite) -> HashMap<String, bool> {
    let mut bindings = HashMap::new();
    for stmt in suite {
        match stmt {
            Stmt::Assign(node) => {
                let is_none = expr_is_none_literal(index, &node.value);
                for target in &node.targets {
                    if let Expr::Name(name) = target {
                        bindings.insert(name.id.to_string(), is_none);
                    }
                }
            }
            Stmt::AnnAssign(node) => {
                let is_none = node
                    .value
                    .as_ref()
                    .is_some_and(|value| expr_is_none_literal(index, value));
                if let Expr::Name(name) = &*node.target {
                    bindings.insert(name.id.to_string(), is_none);
                }
            }
            _ => {}
        }
    }
    bindings
}

fn expr_is_none_like(
    index: &ModuleIndex<'_>,
    expr: &Expr,
    bindings: &HashMap<String, bool>,
) -> bool {
    match expr {
        Expr::Name(name) => bindings.get(name.id.as_str()).copied().unwrap_or(false),
        _ => expr_is_none_literal(index, expr),
    }
}

fn expr_is_none_literal(index: &ModuleIndex<'_>, expr: &Expr) -> bool {
    index.source_slice(expr.range()).trim() == "None"
}

fn module_has_naming_convention(module: &ModuleRecord) -> bool {
    if !module.source.contains("naming_convention") {
        return false;
    }

    let Some(suite) = parse_suite(module) else {
        return false;
    };

    let mut found = false;
    walk_suite_exprs(&suite, &mut |expr| {
        let Expr::Call(call) = expr else {
            return;
        };
        let is_metadata_call = match &*call.func {
            Expr::Name(name) => name.id.as_str() == "MetaData",
            Expr::Attribute(attr) => attr.attr.as_str() == "MetaData",
            _ => false,
        };
        if is_metadata_call
            && call
                .keywords
                .iter()
                .any(|keyword| keyword.arg.as_deref() == Some("naming_convention"))
        {
            found = true;
        }
    });
    if found {
        return true;
    }

    walk_suite_stmts(&suite, &mut |stmt| {
        match stmt {
        Stmt::Assign(node) => {
            if node.targets.iter().any(|target| {
                matches!(target, Expr::Attribute(attr) if attr.attr.as_str() == "naming_convention")
            }) {
                found = true;
            }
        }
        Stmt::AnnAssign(node) => {
            if matches!(&*node.target, Expr::Attribute(attr) if attr.attr.as_str() == "naming_convention")
            {
                found = true;
            }
        }
        _ => {}
    }
    });

    found
}
