use crate::registry::StaticRule;

pub fn parse_static_rule(rule_id: &str) -> Option<StaticRule> {
    Some(match rule_id {
        "architecture/giant-function" => StaticRule::ArchitectureGiantFunction,
        "architecture/deep-nesting" => StaticRule::ArchitectureDeepNesting,
        "architecture/async-without-await" => StaticRule::ArchitectureAsyncWithoutAwait,
        "architecture/import-bloat" => StaticRule::ArchitectureImportBloat,
        "architecture/print-in-production" => StaticRule::ArchitecturePrintInProduction,
        "architecture/star-import" => StaticRule::ArchitectureStarImport,
        "architecture/god-module" => StaticRule::ArchitectureGodModule,
        "architecture/passthrough-function" => StaticRule::ArchitecturePassthroughFunction,
        "architecture/avoid-sys-exit" => StaticRule::ArchitectureAvoidSysExit,
        "architecture/engine-pool-pre-ping" => StaticRule::ArchitectureEnginePoolPrePing,
        "architecture/missing-startup-validation" => {
            StaticRule::ArchitectureMissingStartupValidation
        }
        "architecture/fat-route-handler" => StaticRule::ArchitectureFatRouteHandler,
        "security/forbidden-write-param" => StaticRule::SecurityForbiddenWriteParam,
        "correctness/duplicate-route" => StaticRule::CorrectnessDuplicateRoute,
        "correctness/missing-response-model" => StaticRule::CorrectnessMissingResponseModel,
        "correctness/post-status-code" => StaticRule::CorrectnessPostStatusCode,
        "api-surface/missing-tags" => StaticRule::ApiSurfaceMissingTags,
        "api-surface/missing-docstring" => StaticRule::ApiSurfaceMissingDocstring,
        "api-surface/missing-pagination" => StaticRule::ApiSurfaceMissingPagination,
        "config/direct-env-access" => StaticRule::ConfigDirectEnvAccess,
        "config/alembic-target-metadata" => StaticRule::ConfigAlembicTargetMetadata,
        "config/alembic-empty-autogen-revision" => StaticRule::ConfigAlembicEmptyAutogenRevision,
        "config/sqlalchemy-naming-convention" => StaticRule::ConfigSqlalchemyNamingConvention,
        "correctness/asyncio-run-in-async" => StaticRule::CorrectnessAsyncioRunInAsync,
        "correctness/sync-io-in-async" => StaticRule::CorrectnessSyncIoInAsync,
        "correctness/misused-async-constructs" => StaticRule::CorrectnessMisusedAsyncConstructs,
        "correctness/avoid-os-path" => StaticRule::CorrectnessAvoidOsPath,
        "correctness/deprecated-typing-imports" => StaticRule::CorrectnessDeprecatedTypingImports,
        "correctness/mutable-default-arg" => StaticRule::CorrectnessMutableDefaultArg,
        "correctness/naive-datetime" => StaticRule::CorrectnessNaiveDatetime,
        "correctness/return-in-finally" => StaticRule::CorrectnessReturnInFinally,
        "correctness/threading-lock-in-async" => StaticRule::CorrectnessThreadingLockInAsync,
        "correctness/unreachable-code" => StaticRule::CorrectnessUnreachableCode,
        "correctness/get-with-side-effect" => StaticRule::CorrectnessGetWithSideEffect,
        "correctness/serverless-filesystem-write" => {
            StaticRule::CorrectnessServerlessFilesystemWrite
        }
        "correctness/missing-http-timeout" => StaticRule::CorrectnessMissingHttpTimeout,
        "performance/heavy-imports" => StaticRule::PerformanceHeavyImports,
        "performance/sequential-awaits" => StaticRule::PerformanceSequentialAwaits,
        "performance/regex-in-loop" => StaticRule::PerformanceRegexInLoop,
        "performance/n-plus-one-hint" => StaticRule::PerformanceNPlusOneHint,
        "pydantic/deprecated-validator" => StaticRule::PydanticDeprecatedValidator,
        "pydantic/mutable-default" => StaticRule::PydanticMutableDefault,
        "pydantic/extra-allow-on-request" => StaticRule::PydanticExtraAllowOnRequest,
        "pydantic/should-be-model" => StaticRule::PydanticShouldBeModel,
        "pydantic/sensitive-field-type" => StaticRule::PydanticSensitiveFieldType,
        "security/assert-in-production" => StaticRule::SecurityAssertInProduction,
        "security/cors-wildcard" => StaticRule::SecurityCorsWildcard,
        "security/exception-detail-leak" => StaticRule::SecurityExceptionDetailLeak,
        "security/subprocess-shell-true" => StaticRule::SecuritySubprocessShellTrue,
        "security/unsafe-yaml-load" => StaticRule::SecurityUnsafeYamlLoad,
        "security/weak-hash-without-flag" => StaticRule::SecurityWeakHashWithoutFlag,
        "security/sql-fstring-interpolation" => StaticRule::SecuritySqlFstringInterpolation,
        "security/hardcoded-secret" => StaticRule::SecurityHardcodedSecret,
        "security/pydantic-secretstr" => StaticRule::SecurityPydanticSecretStr,
        "resilience/sqlalchemy-pool-pre-ping" => StaticRule::ResilienceSqlalchemyPoolPrePing,
        "resilience/bare-except-pass" => StaticRule::ResilienceBareExceptPass,
        "resilience/reraise-without-context" => StaticRule::ResilienceReraiseWithoutContext,
        "resilience/exception-swallowed" => StaticRule::ResilienceExceptionSwallowed,
        "resilience/broad-except-no-context" => StaticRule::ResilienceBroadExceptNoContext,
        _ => return None,
    })
}
